# Model arguments
model_name_or_path: Columbia-NLP/gemma-2b-zephyr-sft
torch_dtype: float32

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  trl-lib/kto-mix-14k: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
fp16: true
beta: 0.1
do_eval: true
evaluation_strategy: steps
eval_steps: 500
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1.0
optim: adamw_8bit
output_dir: experiments/kto
per_device_train_batch_size: 1
per_device_eval_batch_size: 2
push_to_hub: false
report_to:
- tensorboard
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
