# Model arguments
# model_name_or_path: google/gemma-2b
model_name_or_path: /home/pratuat/repositories/FactAlign/results/models/gemma-2b/sft/v1/final_merged
torch_dtype: float16
use_flash_attention_2: true # Crucial for H100 performance

# Data training arguments
dataset_mixer:
  # trl-lib/kto-mix-14k: 1.0
  openbmb/UltraFeedback: 1.0
  chaoweihuang/factalign-gemma2-f1_0.75: 1.0
dataset_splits:
- train
# - test
preprocessing_num_workers: 12

# KTOTrainer arguments
deepspeed: /home/pratuat/repositories/FactAlign/configs/deepspeed_zero4.json # Link to the file above
fp16: true
beta: 0.1
desirable_weight: 1.0
loss_type: fg_kto
loss_weight: 1.0
fg_loss_weight: 1.0
fg_beta: 0.1

# Evaluation & Logging
do_eval: true
evaluation_strategy: steps
eval_steps: 200
logging_steps: 10
log_level: info
# report_to:
# - tensorboard
# - wandb

# Optimization Hyperparameters
learning_rate: 5.0e-7
lr_scheduler_type: linear
warmup_ratio: 0.1
num_train_epochs: 3.0
optim: paged_adamw_8bit # Better stability on H100
max_length: 1200
max_prompt_length: 512

# Memory & Throughput
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
per_device_train_batch_size: 2 # You can likely bump this to 2 or 4 on an H100
per_device_eval_batch_size: 2
gradient_accumulation_steps: 8

# Output
output_dir: /home/pratuat/repositories/FactAlign/results/models/gemma-2b/kto/v1
save_strategy: "no"
save_only_model: true
push_to_hub: false
seed: 42
